# Generated by Django 5.0 on 2024-01-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectdetection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pose',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
